version: '2.19'
services:
  install:
    image: install
    build:
      context: .
      dockerfile: Dockerfile.install
  locations-api:
    build:
      context: .
      dockerfile: applications/locations-api/Dockerfile
      target: release
    depends_on:
      - install
    ports:
      - "3000:3000"