version: v1.0
name: Locations api initial build
agent:
  machine:
    type: e2-standard-2
    os_image: ubuntu2004
blocks:
  - name: 📦 Install dependencies
    task:
      env_vars:
        - name: NODE_ENV
          value: ci
      prologue:
        commands:
          - checkout
      jobs:
        - name: install
          commands:
            - bash .semaphore/locations-api/build.sh