name: Build Docker image
 
on:
  push: {}
 
jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ github.ref_name }}-install-deps
      - run: cd monorepo && bun install --frozen-lockfile