name: Deploy to production

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: simon-norman/actions/check-branch@main
        name: Check branch
        with:
          allowed_branch: main
      - uses: simon-norman/actions/deploy@main
        name: Deploy
        with:
          env: production
          file: ./monorepo/applications/locations-api/Dockerfile
          tag: locations-api-production:latest