name: Deploy to staging

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: simon-norman/actions/deploy@main
        name: Deploy
        with:
          env: staging
          file: ./monorepo/applications/locations-api/Dockerfile
          tag: locations-api-staging:latest