name: Deploy Locations API to dev

on:
  workflow_run:
    workflows: ["Build install docker image"]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: monorepo
          file: ./monorepo/applications/locations-api/Dockerfile
          cache-from: type=gha
          push: false
          tags: locations-api:latest
          target: release
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
      - name: Deploy
        run: cd infrastructure && doppler run -p ci-cd -c dev -- pulumi up -s dev