name: Deploy Locations API to dev one

on:
  workflow_run:
    workflows: ["Build install docker image"]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev-1
    steps:
      - uses: simon-norman/actions/deploy@main
        name: Deploy
        with:
          env: dev-1
          file: ./monorepo/applications/locations-api/Dockerfile
          tag: locations-api-dev-1:latest